/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class v_akfz_aff_physics_cpp_NativeBallistics */

#ifndef _Included_v_akfz_aff_physics_cpp_NativeBallistics
#define _Included_v_akfz_aff_physics_cpp_NativeBallistics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     v_akfz_aff_physics_cpp_NativeBallistics
 * Method:    simulateFrame
 * Signature: (Lv/akfz/aff/physics/cpp/CSnapshot;)V
 */
JNIEXPORT void JNICALL Java_v_akfz_aff_physics_cpp_NativeBallistics_simulateFrame
  (JNIEnv *, jclass, jobject);

/*
 * Class:     v_akfz_aff_physics_cpp_NativeBallistics
 * Method:    discard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_v_akfz_aff_physics_cpp_NativeBallistics_discard
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
